### ISSUE TITLE
add option to use saml2 token

### ISSUE THREAD

**Issue by jbuffin** [auth0/node-wsfed#8]
It would be nice if we could generate a saml2 token rather than saml1.

**Comment by siacomuzzi** [comment]
Yes, we could change [this method](https://github.com/auth0/node-wsfed/blob/master/lib/wsfed.js#L79) based on a specific option:

```
(options.saml_version === '2' ? saml20 : saml11).create({
  // ...
});
```

**Comment by jbuffin** [comment]
I have a pull request https://github.com/auth0/node-wsfed/pull/9
